export const shoppingCategories = {
    'furnishing': 'furnishing',
    'gas': 'gas',
    'vehicles': 'vehicles',
    'software': 'software',
    'electronics': 'electronics',
    'computers': 'computers',
    'health': 'health',
    'groceries': 'groceries',
    'fashion': 'fashion',
    'vacation': 'vacation',
    'travel': 'travel',
    'leisure': 'leisure',
    'fitness': 'fitness',
    'commutes': 'commutes',
    'jewelries': 'jewelries',
    'banking': 'banking',
    'clothing': 'clothing',
    'dinning': 'dinning',
    'food': 'food',
    'restaurants': 'restaurants',
    'amazon': 'amazon',
    'target': 'target',
    'baby': 'baby',
    'gym': 'gym',
    'shopping': 'shopping',
    'flights': 'flight'
};